system bubbles
{
    technique 
    {
        visual_particle_quota                   250
        material                                PUMediaPack/Bubble
        renderer                                Billboard
        {
        }
        emitter                                 Line 
        {
            emission_rate                       20
            angle                               10
            time_to_live                        10
            velocity                            dyn_random
            {
                min                             3
                max                             18
            }
            all_particle_dimensions             dyn_random
            {
                min                             1.5
                max                             4.5
            }
            position                            -24 -18 0
            end                                 48 -18 0
        }
    }
    technique 
    {
        visual_particle_quota                   220
        material                                PUMediaPack/BlurredBubble
        renderer                                Billboard
        {
        }
        emitter                                 Line 
        {
            emission_rate                       20
            angle                               10
            time_to_live                        10
            velocity                            dyn_random
            {
                min                             1.5
                max                             6
            }
            all_particle_dimensions             dyn_random
            {
                min                             0.9
                max                             3
            }
            position                            -24 -12 0
            end                                 48 -12 0
        }
    }
}
