system example_021
{
    category                                    Examples_21_30
    technique 
    {
        position                                -24 0 0
        visual_particle_quota                   5000
        emitted_emitter_quota                   1
        material                                ParticleUniverse/Flare
        default_particle_width                  0.9
        default_particle_height                 0.9
        renderer                                Billboard
        {
        }
        emitter                                 Point 
        {
            emission_rate                       1
            angle                               0
            time_to_live                        5
            velocity                            60
            direction                           1 0 0
            emits                               emitter_particle Flares
        }
        emitter                                 SphereSurface Flares
        {
            emission_rate                       3000
            angle                               360
            time_to_live                        dyn_random
            {
                min                             1
                max                             3
            }
            velocity                            dyn_random
            {
                min                             1.8
                max                             7.5
            }
            auto_direction                      true
            radius                              3
        }
        affector                                Colour 
        {
            time_colour                         0    1 0 1 1
            time_colour                         0.5  1 0 0 1
            time_colour                         0.9  0 1 0 1
            time_colour                         1    0 0 0 1
        }
    }
}
