system example_009
{
    category                                    Examples_1_10
    technique 
    {
        visual_particle_quota                   5000
        material                                ParticleUniverse/GreenBall
        default_particle_width                  0.3
        default_particle_height                 0.3
        renderer                                Billboard
        {
        }
        emitter                                 Circle 
        {
            emission_rate                       1000
            angle                               0
            time_to_live                        5
            velocity                            2.1
            direction                           0 0 0
            auto_direction                      true
            radius                              3
            step                                0.2
            emit_random                         false
        }
        affector                                SineForce 
        {
            force_vector                        0 2.4 0
            min_frequency                       5
            max_frequency                       5
        }
    }
}
