system example_015
{
    category                                    Examples_11_20
    technique 
    {
        visual_particle_quota                   3000
        material                                ParticleUniverse/Star
        default_particle_width                  1.5
        default_particle_height                 1.5
        default_particle_depth                  1.5
        renderer                                Billboard
        {
        }
        emitter                                 Box 
        {
            emission_rate                       20
            angle                               10
            time_to_live                        7
            velocity                            6
            box_width                           9
            box_height                          0.3
            box_depth                           9
        }
        affector                                SphereCollider 
        {
            position                            0 12 0
            collision_type                      flow
            radius                              9
        }
    }
}
