system snow
{
    fast_forward                                1 1
    category                                    Nature
    technique 
    {
        visual_particle_quota                   2000
        material                                PUMediaPack/Snow_01
        renderer                                Billboard
        {
            billboard_origin                    top_center
        }
        emitter                                 Box 
        {
            emission_rate                       50
            angle                               dyn_random
            {
                min                             5
                max                             40
            }
            time_to_live                        20
            velocity                            dyn_random
            {
                min                             1.5
                max                             2.7
            }
            all_particle_dimensions             dyn_random
            {
                min                             0.12
                max                             0.48
            }
            position                            0 9 0
            direction                           0 -1 0
            box_width                           24
            box_height                          0.03
            box_depth                           24
        }
        affector                                LinearForce WindLeft
        {
            enabled                             false
            force_vector                        -0.6 0 0
        }
        affector                                LinearForce WindRight
        {
            enabled                             false
            force_vector                        0.6 0 0
        }
        observer                                OnRandom 
        {
            observe_interval                    1
            handler                             DoEnableComponent 
            {
                enable_component                affector_component WindLeft true
            }
            handler                             DoEnableComponent 
            {
                enable_component                affector_component WindRight false
            }
        }
        observer                                OnRandom 
        {
            observe_interval                    1
            handler                             DoEnableComponent 
            {
                enable_component                affector_component WindRight true
            }
            handler                             DoEnableComponent 
            {
                enable_component                affector_component WindLeft false
            }
            random_threshold                    0.6
        }
        observer                                OnPosition 
        {
            handler                             DoPlacementParticle 
            {
                force_emitter                   SplashEmitter
            }
            handler                             DoExpire 
            {
            }
            position_y                          less_than -5.85
        }
    }
    technique 
    {
        visual_particle_quota                   4000
        material                                PUMediaPack/Snow_01
        default_particle_width                  0.48
        default_particle_height                 0.48
        renderer                                Billboard
        {
            billboard_type                      perpendicular_common
            common_direction                    0 1 0
            common_up_vector                    0 0 1
        }
        emitter                                 Point SplashEmitter
        {
            emission_rate                       0
            time_to_live                        100
            direction                           0 0 0
        }
    }
}
