system windyFireSystem
{
    category                                    Fire
    technique 
    {
        material                                ParticleUniverse/Fire
        default_particle_width                  1.8
        default_particle_height                 1.8
        renderer                                Billboard
        {
            render_queue_group                  80
        }
        emitter                                 Point 
        {
            emission_rate                       100
            angle                               30
            time_to_live                        dyn_random
            {
                min                             3
                max                             6
            }
            velocity                            dyn_random
            {
                min                             3
                max                             4.2
            }
        }
        affector                                LinearForce LinearForceRight
        {
            enabled                             false
            force_vector                        3 0 0
        }
        affector                                LinearForce LinearForceLeft
        {
            enabled                             false
            force_vector                        -3 0 0
        }
        affector                                Scale 
        {
            xyz_scale                           -0.15
        }
        affector                                Colour 
        {
            time_colour                         0    1 1 1 1
            time_colour                         1    0 0 0 1
        }
        observer                                OnRandom ObserverRight
        {
            observe_interval                    0.6
            handler                             DoEnableComponent 
            {
                enable_component                affector_component LinearForceLeft false
            }
            handler                             DoEnableComponent 
            {
                enable_component                affector_component LinearForceRight true
            }
            handler                             DoEnableComponent 
            {
                enable_component                observer_component ObserverRight false
            }
            handler                             DoEnableComponent 
            {
                enable_component                observer_component ObserverLeft true
            }
            random_threshold                    0.4
        }
        observer                                OnRandom ObserverLeft
        {
            observe_interval                    0.6
            handler                             DoEnableComponent 
            {
                enable_component                affector_component LinearForceLeft true
            }
            handler                             DoEnableComponent 
            {
                enable_component                affector_component LinearForceRight false
            }
            handler                             DoEnableComponent 
            {
                enable_component                observer_component ObserverRight true
            }
            handler                             DoEnableComponent 
            {
                enable_component                observer_component ObserverLeft false
            }
            random_threshold                    0.6
        }
    }
}
